### PR TITLE
Make options optional

### LINKED ISSUE #4: The second and third options should be declared as optional
https://github.com/maiermic/cycle-storageify/blob/master/src/index.ts#L34-L35

as hard to use from TypeScript

I had to declare a type for the structure and cast it.

### PR DESCRIPTION
**Pull request by jvanbruegge**
Fixes #4

### CODE REVIEW

**Review by SteveALee — COMMENTED** [review]
I think key must always be present! Meaning it's badly name and should be factored out to own parameter

**Comment by jvanbruegge** [comment]
https://github.com/jvanbruegge/cycle-storageify/blob/1eded3bd18d1485fab3ce49e7cacf9337cae02c8/src/index.ts#L40

**Comment by SteveALee** [comment]
ah! :)

**Comment by maiermic** [comment]
@jvanbruegge Thanks, I had the exact same solution in mind :smile:

It is released in version `3.1.0`.

**Comment by SteveALee** [comment]
Thanks very much. Deleting work around now :)

**Pull request merged**
