### PR TITLE
Fix typescript build

### PR DESCRIPTION
**Pull request by jvanbruegge**
Sorry for breaking it.

### CODE REVIEW

**Comment by maiermic** [comment]
Did you added `xstream` version `^11.1.0` to `devDependencies` because npm does not install peer dependencies anymore? That seams like a workaround to me. However, I do not know what best practice is to install type definitions of peer dependencies.

I have concerns about specifying `xstream` as version `>=10.x` in `peerDependencies`. A future version of `xstream` might not be compatible with the current version of `cycle-storageify`. I do not know what best practice is here either.

**Comment by jvanbruegge** [comment]
Yes, the dev dependency is for the peer dependency. AFAIK this is common practise.
For the peer dep, you can either use 10 || 11 or just 11. That was just a quickfix for the peer dep warning

**Comment by maiermic** [comment]
If the current version of `cycle-storageify` is compatible with `xstream` 10 and 11, we don't have to enforce 11. I would suggest to change `xstream` version in `peerDependencies` to `10.x || 11.x`. This should allow us to release your changes in a minor version change (`cycle-storageify` version `4.0.1`). When `xstream` version `12.x` is released we can check if we can add it to `peerDependencies` in another minor version change.

**Comment by jvanbruegge** [comment]
I did the change

**Comment by maiermic** [comment]
Thanks, it is released in version 4.0.1

**Pull request merged**
